// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJGbNtNbt7esA4wtDGdymlmSvKeKa3fTc',
    appId: '1:576588750108:web:74c9fee194632eb09daed9',
    messagingSenderId: '576588750108',
    projectId: 'heartpredictorstates',
    authDomain: 'heartpredictorstates.firebaseapp.com',
    storageBucket: 'heartpredictorstates.appspot.com',
    measurementId: 'G-YCMXJ2V2W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMRXD2jCtYpCaWHJc31HgaWmd9BW0jNOE',
    appId: '1:576588750108:android:2eacf80665c0aeef9daed9',
    messagingSenderId: '576588750108',
    projectId: 'heartpredictorstates',
    storageBucket: 'heartpredictorstates.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHP1siKXJ5b3EU40QdmTR2O_Wajj47zOA',
    appId: '1:576588750108:ios:93a11136985de3bd9daed9',
    messagingSenderId: '576588750108',
    projectId: 'heartpredictorstates',
    storageBucket: 'heartpredictorstates.appspot.com',
    iosBundleId: 'com.example.heartDiseasePredictor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHP1siKXJ5b3EU40QdmTR2O_Wajj47zOA',
    appId: '1:576588750108:ios:f04f309b2000bd1c9daed9',
    messagingSenderId: '576588750108',
    projectId: 'heartpredictorstates',
    storageBucket: 'heartpredictorstates.appspot.com',
    iosBundleId: 'com.example.heartDiseasePredictor.RunnerTests',
  );
}
